/** Report entry from a single Action run */
export interface DashboardReport {
  readonly timestamp: string;
  readonly number: number;
  readonly type: 'pull_request' | 'issues';
  readonly author: string;
  readonly verdict: string;
  readonly totalScore: number;
  readonly signals: readonly string[];
  readonly actionTaken: readonly string[];
}

/**
 * Generate a standalone HTML dashboard from accumulated reports.
 * Uses Chart.js via CDN, inline CSS, responsive.
 * @param reports - array of report entries
 * @returns complete HTML string
 */
export function generateDashboardHtml(
  reports: readonly DashboardReport[],
): string {
  const totalPrs = reports.filter((r) => r.type === 'pull_request').length;
  const totalIssues = reports.filter((r) => r.type === 'issues').length;
  const flagged = reports.filter((r) => r.verdict !== 'clean').length;
  const catchRate =
    reports.length > 0
      ? Math.round((flagged / reports.length) * 100)
      : 0;

  const signalCounts = countSignals(reports);
  const signalLabels = JSON.stringify(Object.keys(signalCounts));
  const signalValues = JSON.stringify(Object.values(signalCounts));

  const dailyCounts = countByDay(reports);
  const dayLabels = JSON.stringify(Object.keys(dailyCounts));
  const dayValues = JSON.stringify(Object.values(dailyCounts));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ai-slop-guard Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
  :root { --bg: #fff; --fg: #111; --card-bg: #f9f9f9; --border: #e0e0e0; }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #1a1a2e; --fg: #eee; --card-bg: #16213e; --border: #333; }
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--fg); padding: 2rem; }
  h1 { font-size: 1.5rem; margin-bottom: 1.5rem; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; }
  .card .value { font-size: 2rem; font-weight: 700; }
  .card .label { font-size: 0.85rem; opacity: 0.7; margin-top: 0.25rem; }
  .charts { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 2rem; }
  .chart-box { background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; }
  canvas { max-height: 300px; }
  footer { margin-top: 2rem; font-size: 0.8rem; opacity: 0.5; }
</style>
</head>
<body>
<h1>ai-slop-guard Dashboard</h1>
<div class="cards">
  <div class="card"><div class="value">${totalPrs}</div><div class="label">PRs analyzed</div></div>
  <div class="card"><div class="value">${totalIssues}</div><div class="label">Issues analyzed</div></div>
  <div class="card"><div class="value">${flagged}</div><div class="label">Flagged</div></div>
  <div class="card"><div class="value">${catchRate}%</div><div class="label">Catch rate</div></div>
</div>
<div class="charts">
  <div class="chart-box"><canvas id="trendChart"></canvas></div>
  <div class="chart-box"><canvas id="signalChart"></canvas></div>
</div>
<footer>Generated by ai-slop-guard</footer>
<script>
new Chart(document.getElementById('trendChart'), {
  type: 'bar',
  data: { labels: ${dayLabels}, datasets: [{ label: 'Flagged items', data: ${dayValues}, backgroundColor: '#E8A317' }] },
  options: { responsive: true, plugins: { title: { display: true, text: 'Trend (last 30 days)' } } }
});
new Chart(document.getElementById('signalChart'), {
  type: 'doughnut',
  data: { labels: ${signalLabels}, datasets: [{ data: ${signalValues}, backgroundColor: ['#E8A317','#D93F0B','#0E8A16','#1D76DB','#5319E7','#FBCA04','#B60205','#006B75'] }] },
  options: { responsive: true, plugins: { title: { display: true, text: 'Top signals' } } }
});
</script>
</body>
</html>`;
}

function countSignals(
  reports: readonly DashboardReport[],
): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const report of reports) {
    for (const signal of report.signals) {
      counts[signal] = (counts[signal] ?? 0) + 1;
    }
  }
  // Return top 8
  return Object.fromEntries(
    Object.entries(counts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 8),
  );
}

function countByDay(
  reports: readonly DashboardReport[],
): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const report of reports) {
    if (report.verdict === 'clean') continue;
    const day = report.timestamp.slice(0, 10);
    counts[day] = (counts[day] ?? 0) + 1;
  }
  return counts;
}
